"use client";

import Badge from "../ui/Badge";

// Placeholder AI insights component for a conversation
export default function AIInsights({ conversationId }: { conversationId: number }) {
  // Mock summary data – in real app this would be generated by an AI service
  const summary = "AI-generated summary of the conversation will appear here. It may include key points, action items, and sentiment analysis.";

  return (
    <div className="p-4 bg-white dark:bg-gray-800 rounded-xl shadow-sm h-full overflow-y-auto">
      <h2 className="text-lg font-medium text-gray-900 dark:text-gray-100 mb-2">AI Insights</h2>
      <p className="text-sm text-gray-600 dark:text-gray-400 mb-2">{summary}</p>
      <Badge variant="new">Sentiment: Positive</Badge>
    </div>
  );
}
